apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-application
spec:
    replicas: 1
    selector:
        matchLabels:
            app: server-application
    template:
        metadata:
            labels:
                app: server-application
        spec:
            containers:
                - name: authorizer
                  image: gcr.io/{my-project-id}/{my-application-image}:latest
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 80
