apiVersion: v1
kind: Service
metadata:
    name: my-application-service

spec:
    type: LoadBalancer
    ports:
        - protocol: TCP
          name: http-svc
          port: 80

    selector:
        app: server-application

